// <auto-generated />
using System;
using AspTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspTest.Migrations
{
    [DbContext(typeof(AspTestDbContext))]
    [Migration("20250826121004_SeedFakeData")]
    partial class SeedFakeData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspTest.Models.Options", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TestId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 1",
                            TestId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 2",
                            TestId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 3",
                            TestId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 4",
                            TestId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 1",
                            TestId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 2",
                            TestId = 2L
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 3",
                            TestId = 2L
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 4",
                            TestId = 2L
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 1",
                            TestId = 3L
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 2",
                            TestId = 3L
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 3",
                            TestId = 3L
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 4",
                            TestId = 3L
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 1",
                            TestId = 4L
                        },
                        new
                        {
                            Id = 14L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 2",
                            TestId = 4L
                        },
                        new
                        {
                            Id = 15L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 3",
                            TestId = 4L
                        },
                        new
                        {
                            Id = 16L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 4",
                            TestId = 4L
                        },
                        new
                        {
                            Id = 17L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 1",
                            TestId = 5L
                        },
                        new
                        {
                            Id = 18L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 2",
                            TestId = 5L
                        },
                        new
                        {
                            Id = 19L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 3",
                            TestId = 5L
                        },
                        new
                        {
                            Id = 20L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 4",
                            TestId = 5L
                        },
                        new
                        {
                            Id = 21L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 1",
                            TestId = 6L
                        },
                        new
                        {
                            Id = 22L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 2",
                            TestId = 6L
                        },
                        new
                        {
                            Id = 23L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 3",
                            TestId = 6L
                        },
                        new
                        {
                            Id = 24L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 4",
                            TestId = 6L
                        },
                        new
                        {
                            Id = 25L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 1",
                            TestId = 7L
                        },
                        new
                        {
                            Id = 26L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 2",
                            TestId = 7L
                        },
                        new
                        {
                            Id = 27L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 3",
                            TestId = 7L
                        },
                        new
                        {
                            Id = 28L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 4",
                            TestId = 7L
                        },
                        new
                        {
                            Id = 29L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 1",
                            TestId = 8L
                        },
                        new
                        {
                            Id = 30L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 2",
                            TestId = 8L
                        },
                        new
                        {
                            Id = 31L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 3",
                            TestId = 8L
                        },
                        new
                        {
                            Id = 32L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 4",
                            TestId = 8L
                        },
                        new
                        {
                            Id = 33L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 1",
                            TestId = 9L
                        },
                        new
                        {
                            Id = 34L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 2",
                            TestId = 9L
                        },
                        new
                        {
                            Id = 35L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 3",
                            TestId = 9L
                        },
                        new
                        {
                            Id = 36L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 4",
                            TestId = 9L
                        },
                        new
                        {
                            Id = 37L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 1",
                            TestId = 10L
                        },
                        new
                        {
                            Id = 38L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 2",
                            TestId = 10L
                        },
                        new
                        {
                            Id = 39L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 3",
                            TestId = 10L
                        },
                        new
                        {
                            Id = 40L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 4",
                            TestId = 10L
                        },
                        new
                        {
                            Id = 41L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 1",
                            TestId = 11L
                        },
                        new
                        {
                            Id = 42L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 2",
                            TestId = 11L
                        },
                        new
                        {
                            Id = 43L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 3",
                            TestId = 11L
                        },
                        new
                        {
                            Id = 44L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 4",
                            TestId = 11L
                        },
                        new
                        {
                            Id = 45L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 1",
                            TestId = 12L
                        },
                        new
                        {
                            Id = 46L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 2",
                            TestId = 12L
                        },
                        new
                        {
                            Id = 47L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 3",
                            TestId = 12L
                        },
                        new
                        {
                            Id = 48L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 4",
                            TestId = 12L
                        },
                        new
                        {
                            Id = 49L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 1",
                            TestId = 13L
                        },
                        new
                        {
                            Id = 50L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 2",
                            TestId = 13L
                        },
                        new
                        {
                            Id = 51L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 3",
                            TestId = 13L
                        },
                        new
                        {
                            Id = 52L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 4",
                            TestId = 13L
                        },
                        new
                        {
                            Id = 53L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 1",
                            TestId = 14L
                        },
                        new
                        {
                            Id = 54L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 2",
                            TestId = 14L
                        },
                        new
                        {
                            Id = 55L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 3",
                            TestId = 14L
                        },
                        new
                        {
                            Id = 56L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 4",
                            TestId = 14L
                        },
                        new
                        {
                            Id = 57L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 1",
                            TestId = 15L
                        },
                        new
                        {
                            Id = 58L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 2",
                            TestId = 15L
                        },
                        new
                        {
                            Id = 59L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 3",
                            TestId = 15L
                        },
                        new
                        {
                            Id = 60L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 4",
                            TestId = 15L
                        },
                        new
                        {
                            Id = 61L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 1",
                            TestId = 16L
                        },
                        new
                        {
                            Id = 62L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 2",
                            TestId = 16L
                        },
                        new
                        {
                            Id = 63L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 3",
                            TestId = 16L
                        },
                        new
                        {
                            Id = 64L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 4",
                            TestId = 16L
                        },
                        new
                        {
                            Id = 65L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 1",
                            TestId = 17L
                        },
                        new
                        {
                            Id = 66L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 2",
                            TestId = 17L
                        },
                        new
                        {
                            Id = 67L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 3",
                            TestId = 17L
                        },
                        new
                        {
                            Id = 68L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 4",
                            TestId = 17L
                        },
                        new
                        {
                            Id = 69L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 1",
                            TestId = 18L
                        },
                        new
                        {
                            Id = 70L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 2",
                            TestId = 18L
                        },
                        new
                        {
                            Id = 71L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 3",
                            TestId = 18L
                        },
                        new
                        {
                            Id = 72L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 4",
                            TestId = 18L
                        },
                        new
                        {
                            Id = 73L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 1",
                            TestId = 19L
                        },
                        new
                        {
                            Id = 74L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 2",
                            TestId = 19L
                        },
                        new
                        {
                            Id = 75L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 3",
                            TestId = 19L
                        },
                        new
                        {
                            Id = 76L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 4",
                            TestId = 19L
                        },
                        new
                        {
                            Id = 77L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 1",
                            TestId = 20L
                        },
                        new
                        {
                            Id = 78L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 2",
                            TestId = 20L
                        },
                        new
                        {
                            Id = 79L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = false,
                            OptionText = "Option 3",
                            TestId = 20L
                        },
                        new
                        {
                            Id = 80L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCorrect = true,
                            OptionText = "Option 4",
                            TestId = 20L
                        });
                });

            modelBuilder.Entity("AspTest.Models.Tests", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 1?"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 2?"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 3?"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 4?"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 5?"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 6?"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 7?"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 8?"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 9?"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 10?"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 11?"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 12?"
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 13?"
                        },
                        new
                        {
                            Id = 14L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 14?"
                        },
                        new
                        {
                            Id = 15L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 15?"
                        },
                        new
                        {
                            Id = 16L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 16?"
                        },
                        new
                        {
                            Id = 17L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 17?"
                        },
                        new
                        {
                            Id = 18L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 18?"
                        },
                        new
                        {
                            Id = 19L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 19?"
                        },
                        new
                        {
                            Id = 20L,
                            CreatedAt = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            QuestionText = "Question 20?"
                        });
                });

            modelBuilder.Entity("AspTest.Models.Users", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "21232f297a57a5a743894a0e4a801fc3",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("TestSessionAnswers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("SelectedOptionId")
                        .HasColumnType("bigint");

                    b.Property<long>("TestSessionTestId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("TestSessionTestId");

                    b.ToTable("TestSessionAnswers");
                });

            modelBuilder.Entity("TestSessionTests", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("TestId")
                        .HasColumnType("bigint");

                    b.Property<long>("TestSessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("TestSessionId");

                    b.ToTable("TestSessionTests");
                });

            modelBuilder.Entity("TestSessions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("TestId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("TestSessions");
                });

            modelBuilder.Entity("AspTest.Models.Options", b =>
                {
                    b.HasOne("AspTest.Models.Tests", "Test")
                        .WithMany("Options")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("TestSessionAnswers", b =>
                {
                    b.HasOne("AspTest.Models.Options", "Option")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TestSessionTests", "TestSessionTest")
                        .WithMany("TestSessionAnswers")
                        .HasForeignKey("TestSessionTestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("TestSessionTest");
                });

            modelBuilder.Entity("TestSessionTests", b =>
                {
                    b.HasOne("AspTest.Models.Tests", "Test")
                        .WithMany("TestSessionTests")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TestSessions", "TestSession")
                        .WithMany("TestSessionTests")
                        .HasForeignKey("TestSessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("TestSession");
                });

            modelBuilder.Entity("TestSessions", b =>
                {
                    b.HasOne("AspTest.Models.Tests", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspTest.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AspTest.Models.Tests", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("TestSessionTests");
                });

            modelBuilder.Entity("TestSessionTests", b =>
                {
                    b.Navigation("TestSessionAnswers");
                });

            modelBuilder.Entity("TestSessions", b =>
                {
                    b.Navigation("TestSessionTests");
                });
#pragma warning restore 612, 618
        }
    }
}
